const _ = require('lodash');

if (!process.argv[2]) {
  console.log('USAGE: npm start -s [filename] [> filename.geojson]');
  console.log('-s: required for npm to not output its own info to stdout');
  console.log('filename: JSON file generated by get_travel_times.py');
  console.log('');
  console.log('By default, prints the generated GeoJSON to stdout. To create a file, pipe the output with "> filename.geojson"');
  process.exit(1);
}

const filename = process.argv[2];

const flatdot = require('./' + filename);

function toGeoJSON(flatdots) {
  return JSON.stringify({
    type: 'FeatureCollection',
    features: flatdots.map(dot =>({
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [dot.lng, dot.lat] // yes, this order
      },
      properties: _.omit(dot, ['lat', 'lng'])
    }))
  }, null, 4);
}

console.log(toGeoJSON(flatdot));
